#! /usr/bin/env perl

use strict;
use warnings;

my $nextBranch = currentBranch();
print $nextBranch;
if ($nextBranch =~ m/([^-]+)-(\d+)/) {
	my $branchName = $1;
	my $stage = $2;
	print "$branchName $stage\n";
}

sub currentBranch {
	my $currentBranch = '';
	my @branches = split "\n", `git branch`;
	while (my $branch = shift @branches) {
		if ($branch =~ m/^\*\s+(\S+)/) {
			$currentBranch = $1;
			last;
		}
	}
	
	return $currentBranch;
}
