#! /usr/bin/env perl

use strict;
use warnings;

my $nextBranch = nextBranch(currentBranch());
print "$nextBranch\n";

sub nextBranch {
	my $nextBranch = shift @_;
	if ($nextBranch =~ m/([^-]+)(-)(\d+)/) {
		my $branchName = $1;
		my $separator = $2;
		my $stage = $3;
		$nextBranch = $branchName . $separator . nextStage($stage);
	}
	return $nextBranch;
}

sub nextStage {
	my $stage = shift @_;
	my $nextStage = scalar($stage) + 1;
	
	if ($nextStage < 10) {
		return "0$nextStage";
	} else {
		return "$nextStage";
	}
}

sub currentBranch {
	my $currentBranch = '';
	my @branches = split "\n", `git branch`;
	while (my $branch = shift @branches) {
		if ($branch =~ m/^\*\s+(\S+)/) {
			$currentBranch = $1;
			last;
		}
	}
	
	return $currentBranch;
}
